
demo:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: postgres
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: elt_dbt